component_depth: 1
languages:
- javascript
exclude:
- node_modules
- /src/server/methods/__mocks__/.*
- /src/app/static/About/.*
- /src/app/static/CaseStudy/.*
- /src/app/static/Privacy/.*
- .*/__mocks__/.*
- /__mocks__/.*
- /webpack.config.prod.js
