language: node_js
node_js:
- 8.8.0
notifications:
  email: false
after_success: npm run coverage
deploy:
  provider: heroku
  app: bechdelviz
  api_key:
    secure: VpqdyI6GV8YUjZ4C712cK6hloenGYJZmLQo4Ill+q9nlDsc4PGyfVA65OoX2JCclJE3XPyUzhCLoWbmNwtND6C/5hxTp6ph3Plp2Kef/VOV2leubHSFnaz3l0fUml2bWMIMemUin7pZ5bGVqqjCUyK5an0ZXEBblmpc9Q5bknl2dxzgXp+/HFx6x42UMTV99kxpMglH/BCkTQO3rj4DNqsO90XR6p7xh01oShS0vRztC1Tz1DIV43TVNWN8ZIo4tffe2rFi5KeLMe8/IzEL/SA+pMFWSAGpPdCy4STuYun9X6j1lwaPqu9ZK7I5UdTjZcefmyYFIu48tzQzYPk7wJEHdht2amsMNz3SB6I3c1iSceGLR/gR7UxGk9ke/Lh6bvK374aMRD6MUYxhrw1z6nASEulsSF1FA+nkNw5XcfAz6R5kFmtlDwXcSHUqVTOO2eML0m/66r4fqTrcSieRwGBAvDFRHZEUs1Xrbnzn8sLzBoIYMcEuWXSS0RLqzRNOYEldbsezJqdqANUeoJkBiYwqL/mBDpJqkrikand01Wpv5bWmF1PBlhrEDf8Xo+Y8ll3YMihNg0tFPHg6A4gpDmKuHPZ6RVrIfdYHmaS6DkEOkCzOAEUV3Q+iwQ/L6xtGWFtyMEeh18EAU+vBJ7KtYW+LUrG1EFhtOh9aLHkCGVp8=
